import json
import time
from copy import deepcopy
from typing import Optional
import re
import ast

from bfcl.constants.category_mapping import VERSION_PREFIX
from bfcl.constants.default_prompts import (
    DEFAULT_USER_PROMPT_FOR_ADDITIONAL_FUNCTION_FC,
    DEFAULT_USER_PROMPT_FOR_ADDITIONAL_FUNCTION_PROMPTING,
    MAXIMUM_STEP_LIMIT,
)
from bfcl.constants.eval_config import RESULT_PATH
from bfcl.eval_checker.multi_turn_eval.multi_turn_utils import (
    STATELESS_CLASSES,
    execute_multi_turn_func_call,
    is_empty_execute_response,
)
from bfcl.model_handler.model_style import ModelStyle
from bfcl.utils import load_file, make_json_serializable, sort_key
from overrides import final

# all APIs can prob share this map
ACTION_REVERT_MAP = {
    "authenticate_travel": "revert_authenticate_travel", # done
    "book_flight": "revert_book_flight", # done
    "cancel_booking": "revert_cancel_booking",  # done
    "compute_exchange_rate": None,
    "contact_customer_support": None,
    "get_all_credit_cards": None,
    "get_budget_fiscal_year": None,
    "get_credit_card_balance": None,
    "get_flight_cost": None,
    "get_nearest_airport_by_city": None,
    "list_all_airports": None,
    "purchase_insurance": "revert_purchase_insurance", # done
    "register_credit_card": "revert_register_credit_card", # done
    "retrieve_invoice": None,
    "set_budget_limit": "revert_set_budget_limit", # done
    "travel_get_login_status": None,
    "verify_traveler_information": None
}


VERIFIER_INSTRUCTION = """
IMPORTANT: ignore the previous instruction to only generate the function calls. 
Below is the interaction history generated by another assistant at addressing the issue. This interaction history may or may not be correct.

First, carefully analyze this previous attempt. What did the assistant do correctly or incorrectly? Use this analysis to make your own answer better. 

After your analysis, output your judgement. If the action for step i is incorrect, enclose the earliest incorrect step in <revert> tag: <revert>i</revert>. Finally, output the correct action for step i in square brackets: [correct_action1(args), correct_action2(args)...]. If the assistant performed all actions correctly, just say No Actions. 

Remember to think step by step when analyzing the assistant's attempt.

If the previous assistant eventually correctly addressed the issue, consider it as correct.
"""

TURN_REVERT_COUNT_LIMIT = 1

#First, carefully analyze this previous attempt. What did the assistant do correctly or incorrectly? Remember to think step by step.
#
#For each step, carefully analyze whether the assistant performed the correct actions or not. If the action for step i is incorrect, enclose the earliest incorrect step in <revert> tag: <revert>step_i</revert>.
#Output the correct action for step i in [].
#For example, if the history is:
#Step 0:
#assistant: step0_correct_actions
#Step 1:
#assistant: step1_incorrect_actions
#
#At the end of you response, you should output:
#<revert>step_1</revert>
#
#[step1_corrected_actions]

def parse_function_call(call_str):
    # Parse the string into an AST
    tree = ast.parse(call_str, mode='eval')
    
    if not isinstance(tree.body, ast.Call):
        raise ValueError("Provided string is not a function call")

    # Get function name
    func_name = tree.body.func.id

    # Get arguments as key-value pairs
    args = {}
    for kw in tree.body.keywords:
        key = kw.arg
        value = ast.literal_eval(kw.value)  # Safely evaluate the literal value
        args[key] = value

    return func_name, args

def extract_revert_number(text: str) -> int:
    match = re.search(r"<revert>(\d+)</revert>", text)
    if match:
        return int(match.group(1))
    return -1

def extract_verifier_action(text: str) -> int:
    matches = re.findall(r'(\[.*?\])', text)
    return matches[-1] if matches else None

def get_last_line(text):
     lines = text.strip().splitlines()  # Remove surrounding whitespace and split into lines
     return lines[-1].strip() if lines else ""  # Return the last line without leading/trailing spaces

class BaseHandler:
    model_name: str
    model_style: ModelStyle

    def __init__(self, model_name, temperature) -> None:
        self.model_name = model_name
        # Replace the slash with underscore to avoid creating subdirectories
        # Replace the dash and dot with underscore for valid variable name
        self.model_name_underline_replaced = (
            model_name.replace("/", "_").replace("-", "_").replace(".", "_")
        )
        self.temperature = temperature
        self.is_fc_model = False  # Whether the model is a function calling model

    def inference(self, test_entry: dict, include_input_log: bool, exclude_state_log: bool):
        # This method is used to retrive model response for each model.

        # FC model
        # TODO: Let all models have the is_fc_model attribute and remove the "FC" check
        if "FC" in self.model_name or self.is_fc_model:
            if "multi_turn" in test_entry["id"]:
                return self.inference_multi_turn_FC(
                    test_entry, include_input_log, exclude_state_log
                )
            else:
                return self.inference_single_turn_FC(test_entry, include_input_log)
        # Prompting model
        else:
            if "multi_turn" in test_entry["id"]:
                return self.inference_multi_turn_prompting(
                    test_entry, include_input_log, exclude_state_log
                )
            else:
                return self.inference_single_turn_prompting(test_entry, include_input_log)

    @final
    def inference_multi_turn_FC(
        self, test_entry: dict, include_input_log: bool, exclude_state_log: bool
    ) -> tuple[list[list], dict]:
        initial_config: dict = test_entry["initial_config"]
        involved_classes: list = test_entry["involved_classes"]
        test_entry_id: str = test_entry["id"]
        test_category: str = test_entry_id.rsplit("_", 1)[0]

        # This is only for the miss function category
        # A mapping from turn index to function to holdout
        holdout_function: dict[int, list] = test_entry.get("missed_function", {})

        total_input_token_count: list[list[float]] = []
        total_output_token_count: list[list[float]] = []
        total_latency: list[list[float]] = []
        all_model_response: list[list] = (
            []
        )  # The model response that will be used for later evaluation
        all_inference_log: list[list[dict]] = (
            []
        )  # The debugging log for human to understand
        force_quit = False  # Whether the model has been forced to quit. If True, this whole entry will be failed.

        # Execute no function call, but just to get a reference to all the instances to get the initial state for logging purpose
        if not exclude_state_log:
            _, involved_instances = execute_multi_turn_func_call(
                [],
                initial_config,
                involved_classes,
                self.model_name_underline_replaced,
                test_entry_id,
                long_context=(
                    "long_context" in test_category or "composite" in test_category
                ),
                is_evaL_run=False,
            )
            state_log = []
            for class_name, class_instance in involved_instances.items():
                if class_name in STATELESS_CLASSES:
                    continue
                # Avoid modification in future turns
                class_instance = deepcopy(class_instance)
                state_log.append(
                    {
                        "role": "state_info",
                        "class_name": class_name,
                        "content": {
                            key: value
                            for key, value in vars(class_instance).items()
                            if not key.startswith("_")
                        },
                    }
                )
            all_inference_log.append(state_log)

        inference_data: dict = {}
        inference_data = self._pre_query_processing_FC(inference_data, test_entry)
        inference_data = self._compile_tools(inference_data, test_entry)

        all_multi_turn_messages: list[list[dict]] = test_entry["question"]
        for turn_idx, current_turn_message in enumerate(all_multi_turn_messages):
            current_turn_message: list[dict]

            if str(turn_idx) in holdout_function:
                test_entry["function"].extend(holdout_function[str(turn_idx)])
                # Since we have added new functions, we need to recompile the tools
                inference_data = self._compile_tools(inference_data, test_entry)
                assert (
                    len(current_turn_message) == 0
                ), "Holdout turn should not have user message."
                current_turn_message = [
                    {
                        "role": "user",
                        "content": DEFAULT_USER_PROMPT_FOR_ADDITIONAL_FUNCTION_FC,
                    }
                ]

            if turn_idx == 0:
                inference_data = self.add_first_turn_message_FC(
                    inference_data, current_turn_message
                )
            else:
                inference_data = self._add_next_turn_user_message_FC(
                    inference_data, current_turn_message
                )

            current_turn_response = []
            current_turn_inference_log: list[dict] = {
                "begin_of_turn_query": current_turn_message
            }
            current_turn_input_token_count: list[float] = []
            current_turn_output_token_count: list[float] = []
            current_turn_latency: list[float] = []

            count = 0
            while True:
                print("-" * 100)
                print(
                    f"ID: {test_entry_id.replace('multi_turn_', '')}, Turn: {turn_idx}, Step: {count}"
                )
                current_step_inference_log: list[dict] = []
                # Add to the current_turn_inference_log at beginning of each step so that we don't need to bother dealing with the break statements
                current_turn_inference_log[f"step_{count}"] = current_step_inference_log

                api_response, query_latency = self._query_FC(inference_data)

                # This part of logging is disabled by default because it is too verbose and will make the result file extremely large
                # It is only useful to see if the inference pipeline is working as expected (eg, does it convert all the inputs correctly)
                if include_input_log:
                    current_step_inference_log.append(
                        {
                            "role": "inference_input",
                            "content": inference_data.get("inference_input_log", ""),
                        }
                    )

                # Try parsing the model response
                model_response_data = self._parse_query_response_FC(api_response)
                model_responses = model_response_data["model_responses"]

                # Add the assistant message to the chat history
                inference_data = self._add_assistant_message_FC(
                    inference_data, model_response_data
                )

                # Process the metadata
                current_turn_input_token_count.append(model_response_data["input_token"])
                current_turn_output_token_count.append(model_response_data["output_token"])
                current_turn_latency.append(query_latency)

                current_turn_response.append(model_responses)
                current_step_inference_log.append(
                    {"role": "assistant", "content": model_responses}
                )

                # Try decoding the model response
                try:
                    decoded_model_responses = self.decode_execute(model_responses)
                    current_step_inference_log.append(
                        {
                            "role": "handler_log",
                            "content": "Successfully decoded model response.",
                            "model_response_decoded": decoded_model_responses,
                        }
                    )

                    if is_empty_execute_response(decoded_model_responses):
                        print("Empty response from the model. Proceed to next turn.")
                        current_step_inference_log.append(
                            {
                                "role": "handler_log",
                                "content": f"Empty response from the model. Proceed to next turn.",
                                "model_response_decoded": decoded_model_responses,
                            }
                        )
                        break

                except Exception as e:
                    print("Failed to decode the model response. Proceed to next turn.")
                    current_step_inference_log.append(
                        {
                            "role": "handler_log",
                            "content": f"Error decoding the model response. Proceed to next turn.",
                            "error": str(e),
                        }
                    )
                    break

                # Obtain the execution results
                execution_results, involved_instances = execute_multi_turn_func_call(
                    decoded_model_responses,
                    initial_config,
                    involved_classes,
                    self.model_name_underline_replaced,
                    test_entry_id,
                    long_context=(
                        "long_context" in test_category or "composite" in test_category
                    ),
                    is_evaL_run=False,
                )

                # Add the execution results to the chat history for the next turn
                inference_data = self._add_execution_results_FC(
                    inference_data, execution_results, model_response_data
                )

                for execution_result in execution_results:
                    current_step_inference_log.append(
                        {
                            "role": "tool",
                            "content": execution_result,
                        }
                    )

                count += 1
                # Force quit after too many steps
                if count > MAXIMUM_STEP_LIMIT:
                    force_quit = True
                    current_step_inference_log.append(
                        {
                            "role": "handler_log",
                            "content": f"Model has been forced to quit after {MAXIMUM_STEP_LIMIT} steps.",
                        }
                    )

                    break

            # Add to the total list
            all_model_response.append(current_turn_response)
            all_inference_log.append(current_turn_inference_log)
            total_input_token_count.append(current_turn_input_token_count)
            total_output_token_count.append(current_turn_output_token_count)
            total_latency.append(current_turn_latency)

            if not exclude_state_log:
                state_log = []
                for class_name, class_instance in involved_instances.items():
                    if class_name in STATELESS_CLASSES:
                        continue
                    # Avoid modification in future turns
                    class_instance = deepcopy(class_instance)
                    state_log.append(
                        {
                            "role": "state_info",
                            "class_name": class_name,
                            "content": {
                                key: value
                                for key, value in vars(class_instance).items()
                                if not key.startswith("_")
                            },
                        }
                    )
                all_inference_log.append(state_log)

            if force_quit:
                break

        metadata = {
            "input_token_count": total_input_token_count,
            "output_token_count": total_output_token_count,
            "latency": total_latency,
            "inference_log": all_inference_log,
        }

        return all_model_response, metadata

    @final
    def inference_multi_turn_prompting(
        self, test_entry: dict, include_input_log: bool, exclude_state_log: bool, react_multi_turn: Optional[bool] = False
    ) -> tuple[list[list], dict]:
        initial_config: dict = test_entry["initial_config"]
        involved_classes: list = test_entry["involved_classes"]
        test_entry_id: str = test_entry["id"]
        test_category: str = test_entry_id.rsplit("_", 1)[0]

        # This is only for the miss function category
        # A mapping from turn index to function to holdout
        holdout_function: dict[int, list] = test_entry.get("missed_function", {})

        total_input_token_count: list[list[float]] = []
        total_output_token_count: list[list[float]] = []
        total_latency: list[list[float]] = []
        # The model response that will be used for later evaluation
        all_model_response: list[list] = []
        # Only for reasoning models, reasoning content will be stored as part of metadata and in inference log
        all_reasoning_content: list[list] = []
        # The debugging log for human to understand
        all_inference_log: list[list[dict]] = []
        force_quit = False  # Whether the model has been forced to quit. If True, this whole entry will be failed.

        # Execute no function call, but just to get a reference to all the instances to get the initial state for logging purpose
        if not exclude_state_log:
            _, involved_instances = execute_multi_turn_func_call(
                [],
                initial_config,
                involved_classes,
                self.model_name_underline_replaced,
                test_entry_id,
                long_context=(
                    "long_context" in test_category or "composite" in test_category
                ),
                is_evaL_run=False,
            )
            state_log = []
            for class_name, class_instance in involved_instances.items():
                if class_name in STATELESS_CLASSES:
                    continue
                # Avoid modification in future turns
                class_instance = deepcopy(class_instance)
                state_log.append(
                    {
                        "role": "state_info",
                        "class_name": class_name,
                        "content": {
                            key: value
                            for key, value in vars(class_instance).items()
                            if not key.startswith("_")
                        },
                    }
                )
            all_inference_log.append(state_log)

        inference_data: dict = self._pre_query_processing_prompting(test_entry)

        all_multi_turn_messages: list[list[dict]] = test_entry["question"]

        task_start_time = time.time()
        task_latency = 0

        turn_latencies = []
        for turn_idx, current_turn_message in enumerate(all_multi_turn_messages):
            turn_start_time = time.time()
            current_turn_message: list[dict]
            # Stores actions performed in the current turn. Used for spec actions
            cur_turn_actions = []

            if str(turn_idx) in holdout_function:
                assert (
                    len(current_turn_message) == 0
                ), "Holdout turn should not have user message."
                current_turn_message = [
                    {
                        "role": "user",
                        "content": DEFAULT_USER_PROMPT_FOR_ADDITIONAL_FUNCTION_PROMPTING.format(
                            functions=holdout_function[str(turn_idx)]
                        ),
                    }
                ]

            if turn_idx == 0:
                inference_data = self.add_first_turn_message_prompting(
                    inference_data, current_turn_message
                )
            else:
                inference_data = self._add_next_turn_user_message_prompting(
                    inference_data, current_turn_message
                )
            
            current_turn_response = []
            current_turn_reasoning_content = []
            current_turn_inference_log: list[dict] = {
                "begin_of_turn_query": current_turn_message
            }
            current_turn_input_token_count: list[float] = []
            current_turn_output_token_count: list[float] = []
            current_turn_latency: list[float] = []

            drafter_trace = []
            # drafter_trace format:
            # drafter_trace[step_i] = [{"assistant": ""}, {"tool": ""}, {"tool": ""}]
            cur_turn_system_prompt = deepcopy(inference_data)

            count = 0
            step_to_inference_data_map = [] # maps the step ID to the object in inference_data. Used to revert
            turn_revert_count = 0 # limit number of reverts to prevent inf loop

            while True:
                print("-" * 100)
                print(
                    f"ID: {test_entry_id.replace('multi_turn_', '')}, Turn: {turn_idx}, Step: {count}"
                )

                current_step_inference_log: list[dict] = []
                # Add to the current_turn_inference_log at beginning of each step so that we don't need to bother dealing with the break statements
                current_turn_inference_log[f"step_{count}"] = current_step_inference_log

                #print("[DEBUG] model input ", inference_data['message'])
                
                drafter_start_time = time.time()
                api_response, query_latency = self._query_prompting(inference_data)
                drafter_end_time = time.time()
                print(f"[STAT] Drafter inference time {drafter_end_time - drafter_start_time}")

                # This part of logging is disabled by default because it is too verbose and will make the result file extremely large
                # It is only useful to see if the inference pipeline is working as expected (eg, does it convert all the inputs correctly)
                if include_input_log:
                    current_step_inference_log.append(
                        {
                            "role": "inference_input",
                            "content": inference_data.get("inference_input_log", ""),
                        }
                    )

                # Try parsing the model response
                model_response_data = self._parse_query_response_prompting(api_response)
                model_responses = model_response_data["model_responses"]

                # Add the assistant message to the chat history
                inference_data = self._add_assistant_message_prompting(
                    inference_data, model_response_data
                )
                #step_to_inference_data_map[count] = inference_data['message'][-1]
                step_to_inference_data_map.append(inference_data['message'][-1])

                # Add new trace entry for current step
                drafter_trace.append([])
                # Add assistant actions
                drafter_trace[count].append({"assistant": model_response_data["model_responses"]})

                # Process the metadata
                current_turn_input_token_count.append(model_response_data["input_token"])
                current_turn_output_token_count.append(model_response_data["output_token"])
                current_turn_latency.append(query_latency)

                current_turn_response.append(model_responses)
                reasoning_content = model_response_data.get("reasoning_content", "")
                current_turn_reasoning_content.append(reasoning_content)

                log_entry = {
                    "role": "assistant",
                    "content": model_responses,
                }
                if reasoning_content:
                    log_entry["reasoning_content"] = reasoning_content

                current_step_inference_log.append(log_entry)

                # Try decoding the model response
                try:
                    if react_multi_turn:
                        print(f"raw model response", model_responses)
                        model_actions = get_last_line(model_responses)
                        print(f"processed model response", model_actions)
                    else:
                        print("not using react!")
                        model_actions = model_responses
                        print(f"Model action", model_actions)

                    decoded_model_responses = self.decode_execute(model_actions)
                    current_step_inference_log.append(
                        {
                            "role": "handler_log",
                            "content": "Successfully decoded model response.",
                            "model_response_decoded": decoded_model_responses,
                        }
                    )

                    cur_turn_actions.append(decoded_model_responses)

                    model_response_data["model_responses_decoded"] = decoded_model_responses
                    if is_empty_execute_response(decoded_model_responses):
                        print("Empty response from the model. Proceed to next turn.")
                        current_step_inference_log.append(
                            {
                                "role": "handler_log",
                                "content": f"Empty response from the model. Proceed to next turn.",
                                "model_response_decoded": decoded_model_responses,
                            }
                        )
                        break

                except Exception as e:
                    print("Failed to decode the model response. Proceed to next turn.")
                    current_step_inference_log.append(
                        {
                            "role": "handler_log",
                            "content": f"Error decoding the model response. Proceed to next turn.",
                            "error": str(e),
                        }
                    )

                    if turn_revert_count == TURN_REVERT_COUNT_LIMIT:
                        print(f"[INFO] Already reverted {TURN_REVERT_COUNT_LIMIT} times in current turn. Continuing to next turn...")
                        break

                    # Turn finished. Invoke verifier
                    # Add verifier instruction in the latest message prompt. Then send it to verifier
                    # Verifier prompt format: 
                    # - Original system prompt + function definitions
                    # - Trajectory of previous turns, if any
                    # - The user task of the current turn
                    # - Verifier instructions
                    # - Current turn drafter trajectory

                    # Orig system prompt + prev turn trajectories + cur user task
                    verifier_input = deepcopy(cur_turn_system_prompt) 
                    # Verifier instructions
                    verifier_input_template = VERIFIER_INSTRUCTION 
                    # Append verifier instructions in last message, which is the current turn task
                    verifier_input['message'][-1]['content'] += verifier_input_template.format(x=count+1) 
                    verifier_input['message'][-1]['content'] += """\nInteraction history of assistant:\n"""
                    # Current turn drafter trajectory
                    for step_id, step_trace in enumerate(drafter_trace): # 
                        verifier_input['message'][-1]['content'] += f"Step {step_id}: {step_trace}\n"

                    # Run verifier 
                    #print("verifier input ", verifier_input)
                    verifier_start_time = time.time()
                    verifier_response, verifier_latency = self._query_prompting(verifier_input)
                    verifier_end_time = time.time()
                    print(f"[STAT] Verifier inference time {verifier_end_time - verifier_start_time}")

                    # vLLM output
                    print(f"===== verifier output {verifier_response.choices[0].text}")
                    # OpenAI API output
                    #print(f"===== verifier output {verifier_response.choices[0].message.content} \n{verifier_response.usage}")

                    #revert_step_number = extract_revert_number(verifier_response.choices[0].message.content)
                    revert_step_number = extract_revert_number(verifier_response.choices[0].text)
                    #print(f"== verifier wants to revert to step {revert_step_number}")
                    # loop through actions that need to be reverted. 
                    # E.g. the drafter performed [act0, act1] in step 0, [act2] in step 1, [act3, act4]
                    # If the verifier decides that step 1 is incorrect, 
                    # then we revert in this order: [act4, act3, act2]
                    if revert_step_number >= 0:
                        turn_revert_count += 1
                        # Verifier decides to revert
                        #print(f"== cur turn all actions {cur_turn_actions}")
                        #print(f"== listing actions to be reverted from step {count} to {revert_step_number} ")
                        for cur_step in reversed(range(revert_step_number, count)):
                            # Iterate through each step to be reverted backwards
                            cur_step_actions = cur_turn_actions[cur_step]
                            print(f"step {cur_step} actions: {cur_step_actions} ")
                            for one_action in reversed(cur_step_actions):
                                # There could be multiple actions per step.
                                # Iterate through each action to be reverted backwards.
                                function_name, arguments = parse_function_call(one_action)
                                if function_name in ACTION_REVERT_MAP and ACTION_REVERT_MAP[function_name] is not None:
                                    revert_function_name = ACTION_REVERT_MAP[function_name]
                                    # Revert this action
                                    print(f"    revert action {one_action} ")
                                    print(f"    function name {function_name}")
                                    print(f"    arguments {arguments}")
                                    if function_name == "cancel_booking":
                                        revert_function_call = [f"{revert_function_name}(booking_id={arguments['booking_id']})"]
                                    elif function_name == "purchase_insurance":
                                        revert_function_call = [f"{revert_function_name}(card_id={arguments['card_id']}, insurance_cost={arguments['insurance_cost']})"]
                                    else:
                                        revert_function_call = [f"{revert_function_name}()"]
                                    print(f"    executing revert function call {revert_function_call}")
                                    out, _ = execute_multi_turn_func_call(
                                        revert_function_call,
                                        initial_config,
                                        involved_classes,
                                        self.model_name_underline_replaced,
                                        test_entry_id,
                                    )
                        # Revert finished. Now execute the verifier action
                        # Decode verifier output
                        try:
                            #verifier_actions = extract_verifier_action(verifier_response.choices[0].message.content)
                            verifier_actions = extract_verifier_action(verifier_response.choices[0].text)
                            print("raw verifier actions: ", verifier_actions)
                            decoded_verifier_actions = self.decode_execute(verifier_actions)
                            print("decoded verifier actions: ", decoded_verifier_actions)
                            model_response_data["model_responses_decoded"] = decoded_verifier_actions

                            if is_empty_execute_response(decoded_verifier_actions):
                                print("Empty response from the verifier. Proceed to next turn.")
                                break
                        except Exception as e:
                            print("Failed to decode the verifier actions. Proceed to next turn.")
                            break
                        ### Remove invalidated drafter actions from history.
                        # Iterate through each chat history to find the earliest step we need to revert to.
                        # Then, delete all chat history after and including that step.
                        # E.g. action1, action2, action3. Verifier reverts to action2.
                        #   need to delete chat history for action2 and action3
                        # The chat history has for following format:
                        #   system message, turn question, step 1 action, step 1 tool response, step 2 action, step 2 tool response etc.
                        # Therefore, if we want to revert i steps, we delete the last 2*i chat history
                        num_steps_to_revert = count - revert_step_number
                        #inference_data['message'] = inference_data['message'][:2*revert_step_number+2]
                        #TODO this is not always correct. Some times its the last 2*i+1 messages.
                        #inference_data['message'] = inference_data['message'][:-num_steps_to_revert*2 or None]  # or None to handle num_steps_to_revert == 0

                        #print("step_to_inference_data_map", step_to_inference_data_map)
                        revert_step_inference_data = step_to_inference_data_map[revert_step_number]
                        revert_step_inference_idx = inference_data['message'].index(revert_step_inference_data)
                        inference_data['message'] = inference_data['message'][:revert_step_inference_idx or None]  # or None to handle num_steps_to_revert == 0

                        # Delete invalidated drafter responses used for evaluation
                        #print("!!! current_turn_response  before ", current_turn_response)
                        current_turn_response = current_turn_response[:-1 or None] # remove the response recorded at the terminating step
                        current_turn_response = current_turn_response[:-num_steps_to_revert or None] 
                        #print("!!! current_turn_response  after ", current_turn_response)

                        cur_turn_actions = cur_turn_actions[:-num_steps_to_revert or None] 
                        cur_turn_actions.append(decoded_verifier_actions)

                        count = revert_step_number # revert step count
                        print("step count reverted back to ", count)
                        # update drafter actions
                        #print("drafter trace before ", drafter_trace)
                        drafter_trace = drafter_trace[:revert_step_number]
                        #print("drafter trace reverted back to ", drafter_trace)
                        drafter_trace.append([]) # add back for current step

                        step_to_inference_data_map = step_to_inference_data_map[:revert_step_number]

                        # Successfully decoded verifier output. execute
                        decoded_model_responses = decoded_verifier_actions 

                        # Extract verifier action and add to the chat history
                        #verifier_response.choices[0].message.content = verifier_actions
                        verifier_response.choices[0].text = verifier_actions
                        verifier_response_data = self._parse_query_response_prompting(verifier_response)
                        #print("== verifier_response before ", verifier_response_data['model_responses_message_for_chat_history'])
                        #verifier_response_data['model_responses_message_for_chat_history'].content = verifier_actions

                        # Add verifier action to trace
                        drafter_trace[count].append({"assistant":verifier_response_data["model_responses"]})

                        inference_data = self._add_assistant_message_prompting(
                            inference_data, verifier_response_data
                        )
                        step_to_inference_data_map.append(inference_data['message'][-1])

                        # Add verifier action to results
                        current_turn_response.append(verifier_actions)
                        print("!!! added verifier out to current_turn_response ", current_turn_response)

                    else: 
                        # verifier happy. finish current turn
                        break

                # Obtain the execution results
                execution_results, involved_instances = execute_multi_turn_func_call(
                    decoded_model_responses,
                    initial_config,
                    involved_classes,
                    self.model_name_underline_replaced,
                    test_entry_id,
                    long_context=(
                        "long_context" in test_category or "composite" in test_category
                    ),
                    is_evaL_run=False,
                )

                # Add the execution results to the chat history for the next turn
                inference_data = self._add_execution_results_prompting(
                    inference_data, execution_results, model_response_data
                )

                for execution_result in execution_results:
                    drafter_trace[count].append({"tool": execution_result})

                for execution_result in execution_results:
                    current_step_inference_log.append(
                        {
                            "role": "tool",
                            "content": execution_result,
                        }
                    )

                count += 1
                # Force quit after too many steps
                if count > MAXIMUM_STEP_LIMIT:
                    force_quit = True
                    current_step_inference_log.append(
                        {
                            "role": "handler_log",
                            "content": f"Model has been forced to quit after {MAXIMUM_STEP_LIMIT} steps.",
                        }
                    )
                    break

            # Add to the total list
            all_model_response.append(current_turn_response)
            all_reasoning_content.append(current_turn_reasoning_content)
            all_inference_log.append(current_turn_inference_log)
            total_input_token_count.append(current_turn_input_token_count)
            total_output_token_count.append(current_turn_output_token_count)
            total_latency.append(current_turn_latency)

            if not exclude_state_log:
                state_log = []
                for class_name, class_instance in involved_instances.items():
                    if class_name in STATELESS_CLASSES:
                        continue
                    # Avoid modification in future turns
                    class_instance = deepcopy(class_instance)
                    state_log.append(
                        {
                            "role": "state_info",
                            "class_name": class_name,
                            "content": {
                                key: value
                                for key, value in vars(class_instance).items()
                                if not key.startswith("_")
                            },
                        }
                    )
                all_inference_log.append(state_log)
            

            turn_end_time = time.time()
            turn_latencies.append(turn_end_time - turn_start_time)

            if force_quit:
                break

        metadata = {
            "input_token_count": total_input_token_count,
            "output_token_count": total_output_token_count,
            "latency": total_latency,
            "inference_log": all_inference_log,
        }
        # We only include reasoning content if it exists and is not empty
        if not all(
            all(content == "" for content in single_turn_reasoning_content)
            for single_turn_reasoning_content in all_reasoning_content
        ):
            metadata["reasoning_content"] = all_reasoning_content

        task_end_time = time.time()
        task_latency = task_end_time - task_start_time 
        print(f"[STAT] Task {test_entry_id} total latency = {task_latency}")
        print(f"[STAT] Turn latencies: {turn_latencies}")

        return all_model_response, metadata

    @final
    def inference_single_turn_FC(
        self, test_entry: dict, include_input_log: bool
    ) -> tuple[any, dict]:
        inference_data: dict = {}
        inference_data = self._pre_query_processing_FC(inference_data, test_entry)
        inference_data = self._compile_tools(inference_data, test_entry)
        inference_data = self.add_first_turn_message_FC(
            inference_data, test_entry["question"][0]
        )

        api_response, query_latency = self._query_FC(inference_data)

        # Try parsing the model response
        model_response_data = self._parse_query_response_FC(api_response)

        # Process the metadata
        metadata = {}
        if include_input_log:
            metadata["inference_log"] = [
                {
                    "role": "inference_input",
                    "content": inference_data.get("inference_input_log", ""),
                }
            ]
        metadata["input_token_count"] = model_response_data["input_token"]
        metadata["output_token_count"] = model_response_data["output_token"]
        metadata["latency"] = query_latency

        return model_response_data["model_responses"], metadata

    @final
    def inference_single_turn_prompting(
        self, test_entry: dict, include_input_log: bool
    ) -> tuple[any, dict]:
        inference_data: dict = self._pre_query_processing_prompting(test_entry)
        inference_data = self.add_first_turn_message_prompting(
            inference_data, test_entry["question"][0]
        )

        api_response, query_latency = self._query_prompting(inference_data)

        # Try parsing the model response
        model_response_data = self._parse_query_response_prompting(api_response)

        # Process the metadata
        metadata = {}
        if include_input_log:
            metadata["inference_log"] = [
                {
                    "role": "inference_input",
                    "content": inference_data.get("inference_input_log", ""),
                }
            ]
        metadata["input_token_count"] = model_response_data["input_token"]
        metadata["output_token_count"] = model_response_data["output_token"]
        metadata["latency"] = query_latency

        if "reasoning_content" in model_response_data:
            metadata["reasoning_content"] = model_response_data["reasoning_content"]

        return model_response_data["model_responses"], metadata

    def decode_ast(self, result, language="Python"):
        """
        This method takes raw model output (from `_parse_query_response_xxx`) and convert it to standard AST checker input.
        """
        raise NotImplementedError

    def decode_execute(self, result):
        """
        This method takes raw model output (from `_parse_query_response_xxx`) and convert it to standard execute checker input.
        """
        raise NotImplementedError

    @final
    def write(self, result, result_dir, update_mode=False):
        model_name_dir = self.model_name.replace("/", "_")
        model_result_dir = result_dir / model_name_dir
        model_result_dir.mkdir(parents=True, exist_ok=True)

        if isinstance(result, dict):
            result = [result]

        # Collect and format each entry for JSON compatibility
        entries_to_write = [make_json_serializable(entry) for entry in result]

        # Group entries by their `test_category` for efficient file handling
        file_entries = {}
        for entry in entries_to_write:
            test_category = entry["id"].rsplit("_", 1)[0]
            file_name = f"{VERSION_PREFIX}_{test_category}_result.json"
            file_path = model_result_dir / file_name
            file_entries.setdefault(file_path, []).append(entry)

        for file_path, entries in file_entries.items():
            if update_mode:
                # Load existing entries from the file
                existing_entries = {}
                if file_path.exists():
                    existing_entries = {
                        entry["id"]: entry for entry in load_file(file_path)
                    }

                # Update existing entries with new data
                for entry in entries:
                    existing_entries[entry["id"]] = entry

                # Sort entries by `id` and write them back to ensure order consistency
                sorted_entries = sorted(existing_entries.values(), key=sort_key)
                with open(file_path, "w") as f:
                    for entry in sorted_entries:
                        f.write(json.dumps(entry) + "\n")

            else:
                # Normal mode: Append in sorted order
                entries.sort(key=sort_key)
                with open(file_path, "a") as f:
                    for entry in entries:
                        f.write(json.dumps(entry) + "\n")

    #### FC methods ####

    def _query_FC(self, inference_data: dict):
        """
        Call the model API in FC mode to get the response.
        Return the response object that can be used to feed into the `_parse_query_response_FC` method.
        """
        raise NotImplementedError

    def _pre_query_processing_FC(self, inference_data: dict, test_entry: dict) -> dict:
        """
        Preprocess the testset entry before sending it to the model.
        This might includes transforming the input user message into the format expected by the model, extract out the system prompt (if any), and any other necessary preprocessing steps. Those steps can also be done in the `add_first_turn_message_FC` and `_add_next_turn_user_message_FC` methods, but it's usually cleaner to do it here.
        The inference_data dict is updated in place and returned.

        Note: This method has different signature from its Prompting version.
        """
        raise NotImplementedError

    def _compile_tools(self, inference_data: dict, test_entry: dict) -> dict:
        """
        [Only for FC mode]
        This method is used to prepare/compile the tools from the test entry and add them to the inference data to use for model query in FC mode.
        Function docs usually need to be transformed to the format expected by the model, done through the `convert_to_tool` function from `model_handler/utils.py`.
        The inference_data dict is updated in place and returned.
        """
        raise NotImplementedError

    def _parse_query_response_FC(self, api_response: any) -> dict:
        """
        Parses the raw response from the model API to extract the result, input token count, and output token count.

        Args:
            api_response (any): The raw response from the model API.

        Returns:
            A dict containing the following elements:
                - model_responses (any): The parsed result that can be directly used as input to the decode method.
                - input_token (int): The number of tokens used in the input to the model.
                - output_token (int): The number of tokens generated by the model as output.
                - tool_call_ids (list[str]): The IDs of the tool calls that are generated by the model. Optional.
                - Any other metadata that is specific to the model.
        """
        raise NotImplementedError

    def add_first_turn_message_FC(
        self, inference_data: dict, first_turn_message: list[dict]
    ) -> dict:
        """
        Add the first turn message to the chat history, in the format that the model expects.

        Args:
            inference_data (dict): The inference data from previous processing steps.
            first_turn_message (list[dict]): The first turn message from the test entry. It has variable length. It might contain one or more of the following roles:
                - "system": The system message. This role will only appear at most once, at the beginning of the first turn. For most entry, this role will not appear.
                - "user": The user message.
                - "assistant": The assistant message. For most entry, this role will not appear.

        Returns:
            inference_data (dict): The updated inference data that will be send to `_query_FC` to call the model API.
        """
        raise NotImplementedError

    def _add_next_turn_user_message_FC(
        self, inference_data: dict, user_message: list[dict]
    ) -> dict:
        """
        [Only for multi-turn]
        Add next turn user message to the chat history for query.
        user_message is a list of 1 element, which is guaranteed to be a `user` role message.
        """
        raise NotImplementedError

    def _add_assistant_message_FC(
        self, inference_data: dict, model_response_data: dict
    ) -> dict:
        """
        Add assistant message to the chat history.
        """
        raise NotImplementedError

    def _add_execution_results_FC(
        self, inference_data: dict, execution_results: list[str], model_response_data: dict
    ) -> dict:
        """
        Add the execution results to the chat history to prepare for the next turn of query.
        Some models may need to add additional information to the chat history, such as tool call IDs.
        """
        raise NotImplementedError

    #### Prompting methods ####

    def _query_prompting(self, inference_data: dict):
        """
        Call the model API in prompting mode to get the response.
        Return the response object that can be used to feed into the decode method.
        """
        raise NotImplementedError

    def _pre_query_processing_prompting(self, test_entry: dict) -> dict:
        """
        Preprocess the testset entry before sending it to the model.
        This might includes transforming the input user message into the format expected by the model, extract out the system prompt (if any), and any other necessary preprocessing steps. Those steps can also be done in the `add_first_turn_message_prompting` and `_add_next_turn_user_message_prompting` methods, but it's usually cleaner to do it here.
        The function docs are usually supplied to the prompting models as part of the system prompt, done via the `system_prompt_pre_processing_chat_model` function from `model_handler/utils.py`, unless the model has a different way of handling it.
        Returns a dict that contains all the necessary information for the query method.
        Things like `system_prompt` and `chat_history` are optional, specific to the model.

        Note: This method has different signature from its FC version.
        """
        raise NotImplementedError

    def _parse_query_response_prompting(self, api_response: any) -> dict:
        """
        Parses the raw response from the model API to extract the result, input token count, and output token count.

        Args:
            api_response (any): The raw response from the model API.

        Returns:
            A dict containing the following elements:
                - model_responses (any): The parsed result that can be directly used as input to the decode method.
                - input_token (int): The number of tokens used in the input to the model.
                - output_token (int): The number of tokens generated by the model as output.
                - Any other metadata that is specific to the model.
        """
        raise NotImplementedError

    def add_first_turn_message_prompting(
        self, inference_data: dict, first_turn_message: list[dict]
    ) -> dict:
        """
        Add the first turn message to the chat history, in the format that the model expects.

        Args:
            inference_data (dict): The inference data from previous processing steps.
            first_turn_message (list[dict]): The first turn message from the test entry. It has variable length. It might contain one or more of the following roles:
                - "system": The system message. This role will only appear at most once, at the beginning of the first turn.
                - "user": The user message.
                - "assistant": The assistant message. For most entry, this role will not appear.

        Returns:
            inference_data (dict): The updated inference data that will be send to `_query_prompting` to call the model API.
        """
        raise NotImplementedError

    def _add_next_turn_user_message_prompting(
        self, inference_data: dict, user_message: list[dict]
    ) -> dict:
        """
        [Only for multi-turn]
        Add next turn user message to the chat history for query.
        user_message is a list of 1 element, which is guaranteed to be a `user` role message.
        """
        raise NotImplementedError

    def _add_assistant_message_prompting(
        self, inference_data: dict, model_response_data: dict
    ) -> dict:
        """
        Add assistant message to the chat history.
        """
        raise NotImplementedError

    def _add_execution_results_prompting(
        self, inference_data: dict, execution_results: list[str], model_response_data: dict
    ) -> dict:
        """
        Add the execution results to the chat history to prepare for the next turn of query.
        By default, execution results are added back as a `user` role message, as most models don't support the `tool` role in prompting mode.
        """
        raise NotImplementedError
